name: node_build_and_deploy

env:
  MY_VAR: aurélien

# trigger
on:
  # push: { branches: [main] }
  workflow_dispatch:

jobs:
  build-fucking-step:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v6
      - name: setup node
        uses: actions/setup-node@v6
        with:
          node-version: 24.x
      - name: install
        run: npm ci
      - name: build
        run: npm run build
      - name: upload artifact
        uses: actions/upload-artifact@v7
        with:
          path: |
            dist
            package.json
            package-lock.json
          name: build
  deploy:
    needs: build-fucking-step
    runs-on: ubuntu-latest
    steps:
      - name: download artifact
        uses: actions/download-artifact@v8
        with:
          path: api
          name: build

      - name: Deploy to Server
        uses: wlixcc/SFTP-Deploy-Action@v1.2.6
        with:
          username: khunly
          server: ssh-khunly.alwaysdata.net
          port: 22
          password: ${{ secrets.FTP_PASSWORD }}
          local_path: ./api/*
          remote_path: /home/khunly
  install:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Install Node Module
        uses: appleboy/ssh-action@v1
        with:
          host: ssh-khunly.alwaysdata.net
          port: 22
          username: khunly
          password: ${{ secrets.FTP_PASSWORD }}
          script: |
            npm ci --production
            pkill -9 -f "node dist/app.js"