name: node

env: 
    MY_VAR: aurélien

# trigger
on: 
    # push: { branches: [main] }
    workflow_dispatch:
    
jobs: 
    build_and_test:
        runs-on: windows-latest
        steps: 
            - name: show dir
              run: dir
            - name: checkout
              uses: actions/checkout@v6
            - name: show dir after checkout
              run: dir