name: node

env: 
    MY_VAR: aurélien

# trigger
on: 
    # push: { branches: [main] }
    workflow_dispatch:
    
jobs: 
    build_and_test:
        runs-on: ubuntu-latest
        steps: 
            - name: show dir
              run: ls -a -l
            - name: checkout
              uses: actions/checkout@v6
            - name: show dir after checkout
              run: ls -a -l
            - name: setup node
              uses: actions/setup-node@v6
              with:
                node-version: 24.x
            - name: build
              run: npm run build
            - name: check build
              run: npm start