name: node

env: 
    MY_VAR: aurélien

# trigger
on: 
    # push: { branches: [main] }
    workflow_dispatch:
    
jobs: 
    build_and_test:
        runs-on: ubuntu-latest
        steps: 
            - name: show dir
              run: ls -a -l
            - name: checkout
              uses: actions/checkout@v6
            - name: show dir after checkout
              run: ls -a -l
            - name: setup node
              uses: actions/setup-node@v6
              with:
                node-version: 24.x
            - name: install
              run: npm ci
            - name: test
              run: npm test
            - name: send mail if fail
              if: failure()
              uses: JaSiLez/smtp-notifier@main
              with:
                server_address: ssl0.ovh.net
                server_port: 465
                secure: true
                username: aurelien@khunly.be
                password: ${{secrets.SMTP_PWD}}
                subject: ${{ github.workflow_ref }} has failed
                html_body: <p>Les tests ont échoués</p>
                from: aurelien@khunly.be
                to: khun.ly@bstorm.be
            - name: build
              run: npm run build
            - name: check build
              run: npm start
            